### ISSUE TITLE
undefined symbol: FT_Get_Var_Blend_Coordinates

### ISSUE THREAD

**Issue by phipolis** [UnitedRPMs/freetype-freeworld#1]
The freetype-freeworld breaks at least chromium-freeworld, and probably other packages, saying:

`/usr/lib64/chromium/chromium: symbol lookup error: /lib64/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates`

This is Fedora 26 with freetype-freeworld-2.7-2.fc26.x86_64 and chromium-freeworld-59.0.3071.115-2.fc26.x86_64. Removing freetype-freeworld fixes the problem.

[Related issue](https://bugzilla.redhat.com/show_bug.cgi?id=1410528)

**Comment by kuboosoft** [comment]
@phipolis Thank you for your report, we will review what happened with freetype-freeworld; Generally I do not use. But if it is affecting chromium-freeworld and others it is urgent....

**Comment by kuboosoft** [comment]
The current update (2.8) should solve the problem. Please update and install freetype-freeworld if is necessary.

```
su
dnf clean all && dnf -y update
```

**Comment by phipolis** [comment]
Yep, seems fixed! Thanks for the speedy response on this!
